name: Start Issue Automation Task
description: Posts a start message and parses the issue
branding:
  icon: activity
  color: blue

inputs:
  token:
    description: Personal Access Token
    required: true
  issue-template:
    description: Issue Template File Name (e.g. 'example_template.md')
    required: true
  issue-number:
    description: Issue Number
    required: true
    default: ${{ github.event.issue.number }}
  issue-body:
    description: Issue Body
    required: true
    default: ${{ github.event.issue.body }}
  start-message:
    description: Start Message
    required: true

outputs:
  config:
    description: Configuration in JSON format
    value: ${{ steps.parse-issue.outputs.result }}
  error:
    description: Parsing error (empty if none occurred)
    value: ${{ steps.parse-issue.outputs.error }}

runs:
  using: composite
  steps:

    - name: Assign & Comment
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
        GITHUB_TOKEN: ${{ inputs.token }}
        START_MESSAGE: ${{ inputs.start-message }}
      run: |
        username="$(gh api /user | jq -r '.login')"
        gh issue edit $ISSUE_NUMBER --repo "$REPOSITORY" --add-assignee "$username"

        sleep 0.5

        gh issue comment $ISSUE_NUMBER --repo "$REPOSITORY" --body "$START_MESSAGE"

    - name: Parse Issue
      id: parse-issue
      uses: nodes-app/action-issue-to-json@v1
      with:
        issue-body: ${{ inputs.issue-body }}
        template: ${{ inputs.issue-template }}
